"use client";
import { ChevronDown, ExternalLink, MapPin, Pencil, Phone } from "lucide-react";
import { useState } from "react";
import type { Store } from "../types/storeTypes";

export function StoresPanel({ onEdit, stores }: { onEdit?: (store: Store) => void; stores: Store[] }) {
  const [openId, setOpenId] = useState<string | null>(null);
  return <div className="grid items-start gap-4 md:grid-cols-2">{stores.map((store) => {
    const open = openId === store.id;
    return <article className="overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm" key={store.id}><div className="p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-sm text-slate-500">{store.manager}</p><h3 className="mt-1 text-xl font-semibold">{store.name}</h3></div><button aria-label="Editar loja" className="rounded-md border border-slate-200 p-2 hover:bg-amber-50" onClick={() => onEdit?.(store)} title="Editar informações desta loja" type="button"><Pencil size={17} /></button></div><div className="mt-5 grid grid-cols-2 gap-3 text-sm"><div><span className="text-slate-500">Meta mensal</span><strong className="block">{store.monthlyGoal}</strong></div><div><span className="text-slate-500">Saldo atual</span><strong className="block text-emerald-700">{store.balance}</strong></div></div><button aria-expanded={open} className="mt-4 inline-flex items-center gap-2 text-sm font-semibold text-cyan-700" onClick={() => setOpenId(open ? null : store.id)} type="button">{open ? "Ocultar detalhes" : "Ver detalhes"}<ChevronDown className={open ? "rotate-180" : ""} size={16} /></button>{open ? <div className="mt-4 border-t border-slate-100 pt-4">{store.photoUrl ? <div aria-label={`Fachada da ${store.name}`} className="mb-4 h-44 w-full rounded-md bg-cover bg-center" role="img" style={{ backgroundImage: `url(${store.photoUrl})` }} /> : null}<div className="space-y-2 text-sm text-slate-600">{store.address ? <p className="flex gap-2"><MapPin className="mt-0.5 shrink-0" size={16} />{store.address}, {store.city}/{store.state} · CEP {store.cep}</p> : <p>Endereço não informado.</p>}{store.phone ? <p className="flex items-center gap-2"><Phone size={16} />{store.phone}</p> : null}{store.mapsUrl ? <a className="inline-flex items-center gap-2 font-semibold text-cyan-700" href={store.mapsUrl} rel="noreferrer" target="_blank">Abrir no Google Maps <ExternalLink size={14} /></a> : null}</div></div> : null}</div></article>;
  })}</div>;
}
