export type AccountPayable = {
  id: string;
  supplier: string;
  store: string;
  dueDate: string;
  amount: string;
  installment: string;
  dailyInterestAmount?: string;
  dailyInterestPercent?: string;
  lateFeeAmount?: string;
  lateFeePercent?: string;
  protestAfterDays?: string;
  paidAt?: string;
  receiptName?: string;
  receiptPath?: string;
  receiptUrl?: string;
  status: "Aberto" | "Pago" | "Atrasado";
  fixedExpenseId?: string;
  referenceMonth?: string;
};
