"use client";

import { Building2, CheckCircle2, ChevronRight, Sparkles } from "lucide-react";
import { useState } from "react";
import { TextField } from "@/components/ui/TextField";
import type { AppUser } from "@/features/auth/types/authTypes";

export function FirstAccessOnboarding({ onComplete, user }: { onComplete: (companyName: string) => Promise<void>; user: AppUser }) {
  const [companyName, setCompanyName] = useState(""); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  async function finish(name: string) { setLoading(true); setError(""); try { await onComplete(name); } catch { setError("Não foi possível preparar seu ambiente. Tente novamente."); } finally { setLoading(false); } }
  return <main className="flex min-h-screen items-center justify-center bg-slate-100 p-5"><div className="w-full max-w-3xl overflow-hidden rounded-lg border border-slate-200 bg-white shadow-xl"><header className="bg-slate-950 px-7 py-8 text-white"><div className="flex items-center gap-3 text-cyan-300"><Sparkles size={22} /><span className="text-sm font-semibold uppercase">Primeiro acesso</span></div><h1 className="mt-3 text-3xl font-bold">Bem-vindo ao Orquestra Hub, {user.name.split(" ")[0]}.</h1><p className="mt-2 text-slate-300">Vamos preparar um ambiente financeiro vazio e exclusivo para o seu negócio.</p></header><div className="grid gap-7 p-7 md:grid-cols-2"><section><h2 className="font-semibold">Cadastre sua primeira empresa</h2><p className="mt-1 text-sm text-slate-600">Você poderá adicionar outras empresas e convidar novos Proprietários depois.</p><div className="mt-5"><TextField label="Nome da empresa" onChange={(event) => setCompanyName(event.target.value)} placeholder="Ex.: Caixa Moda" value={companyName} /></div>{error ? <p className="mt-3 text-sm text-rose-700">{error}</p> : null}<button className="mt-4 inline-flex h-11 w-full items-center justify-center gap-2 rounded-md bg-cyan-700 px-4 text-sm font-semibold text-white disabled:opacity-60" disabled={loading || !companyName.trim()} onClick={() => finish(companyName)} type="button"><Building2 size={18} />Criar empresa e continuar</button><button className="mt-3 inline-flex h-11 w-full items-center justify-center gap-2 rounded-md border border-slate-300 px-4 text-sm font-semibold text-slate-700 disabled:opacity-60" disabled={loading} onClick={() => finish("")} type="button">Pular por enquanto <ChevronRight size={17} /></button></section><section className="rounded-md bg-slate-50 p-5"><h2 className="font-semibold">Seu ambiente começa assim</h2><div className="mt-4 space-y-3 text-sm text-slate-700">{["Perfil Proprietário com acesso completo", "Nenhum dado demonstrativo", "Cadastros e finanças totalmente zerados", "Separação segura por empresa", "Convites para Financeiro, Consulta ou outro Proprietário"].map((item) => <p className="flex gap-2" key={item}><CheckCircle2 className="shrink-0 text-emerald-600" size={18} />{item}</p>)}</div></section></div></div></main>;
}
