"use client";

import { Download, ExternalLink, ShieldCheck, Trash2 } from "lucide-react";
import { useState } from "react";
import type { AppUser } from "@/features/auth/types/authTypes";
import { requestAccountDeletion } from "../services/privacyService";

export function PrivacyPanel({ exportData, user }: { exportData: Record<string, unknown>; user: AppUser }) {
  const [reason, setReason] = useState(""); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false);
  function download() { const payload = JSON.stringify({ company: user.companyName, exportedAt: new Date().toISOString(), user: { email: user.email, name: user.name, role: user.role }, ...exportData }, null, 2); const url = URL.createObjectURL(new Blob([payload], { type: "application/json" })); const link = document.createElement("a"); link.href = url; link.download = `dados-lgpd-${user.companyName.toLocaleLowerCase("pt-BR").replace(/[^a-z0-9]+/g, "-")}.json`; link.click(); URL.revokeObjectURL(url); }
  async function requestDeletion() { if (!window.confirm("Enviar uma solicitação formal de exclusão da sua conta? Os dados sujeitos a obrigação legal poderão ser conservados pelo prazo necessário.")) return; setLoading(true); try { const protocol = await requestAccountDeletion(user, reason); setMessage(`Solicitação registrada. Protocolo: ${protocol}.`); setReason(""); } catch { setMessage("Não foi possível registrar a solicitação."); } finally { setLoading(false); } }
  return <section className="rounded-lg border border-slate-200 bg-white shadow-sm"><header className="border-b border-slate-200 px-5 py-4"><div className="flex items-center gap-3"><ShieldCheck className="text-cyan-700" size={21} /><div><h3 className="font-semibold">Privacidade e LGPD</h3><p className="text-sm text-slate-500">Acesso, portabilidade e exclusão de dados pessoais.</p></div></div></header><div className="grid gap-5 p-5 lg:grid-cols-2"><article><h4 className="font-semibold">Exportar meus dados</h4><p className="mt-1 text-sm text-slate-600">Baixa os dados da empresa atual e as informações do seu perfil em JSON.</p><button className="mt-4 inline-flex items-center gap-2 rounded-md bg-slate-950 px-4 py-2 text-sm font-semibold text-white" onClick={download} type="button"><Download size={17} />Exportar dados</button><div className="mt-4 flex gap-4 text-sm"><a className="inline-flex items-center gap-1 font-semibold text-cyan-700" href="/privacidade" target="_blank">Privacidade <ExternalLink size={14} /></a><a className="inline-flex items-center gap-1 font-semibold text-cyan-700" href="/termos" target="_blank">Termos <ExternalLink size={14} /></a></div></article><article><h4 className="font-semibold text-rose-800">Solicitar exclusão</h4><p className="mt-1 text-sm text-slate-600">A solicitação será analisada antes da remoção definitiva para preservar documentos exigidos por lei e os direitos dos demais Proprietários.</p><textarea className="mt-3 min-h-24 w-full rounded-md border border-slate-300 p-3 text-sm" onChange={(event) => setReason(event.target.value)} placeholder="Motivo opcional" value={reason} /><button className="mt-3 inline-flex items-center gap-2 rounded-md border border-rose-300 px-4 py-2 text-sm font-semibold text-rose-700 hover:bg-rose-50 disabled:opacity-60" disabled={loading} onClick={requestDeletion} type="button"><Trash2 size={17} />{loading ? "Enviando..." : "Solicitar exclusão da conta"}</button>{message ? <p className="mt-3 text-sm font-medium text-slate-700">{message}</p> : null}</article></div></section>;
}
