import { Bell, CalendarClock } from "lucide-react";
import { SelectField } from "@/components/ui/SelectField";
import { TextField } from "@/components/ui/TextField";
import { formatBRL, toTitleCaseBR } from "@/lib/formatters/br";
import type { FixedExpense } from "../types/fixedExpenseTypes";
export type FixedExpenseForm = { alertDays: string; amount: string; category: string; dueDay: string; name: string; payee: string; store: string };
export function FixedExpensesPanel({ expenses, form, onChange, onSubmit, storeOptions }: { expenses: FixedExpense[]; form: FixedExpenseForm; onChange: (form: FixedExpenseForm) => void; onSubmit: () => void; storeOptions: string[] }) {
  return <div className="space-y-4"><div className="grid gap-4 rounded-lg border border-slate-200 bg-white p-5 shadow-sm md:grid-cols-2 xl:grid-cols-4"><TextField label="Despesa" onBlur={() => onChange({ ...form, name: toTitleCaseBR(form.name) })} onChange={(e) => onChange({ ...form, name: e.target.value })} placeholder="Ex.: Aluguel" value={form.name} /><TextField label="Categoria" onBlur={() => onChange({ ...form, category: toTitleCaseBR(form.category) })} onChange={(e) => onChange({ ...form, category: e.target.value })} placeholder="Ex.: Estrutura" value={form.category} /><TextField label="Favorecido" onBlur={() => onChange({ ...form, payee: toTitleCaseBR(form.payee) })} onChange={(e) => onChange({ ...form, payee: e.target.value })} placeholder="Nome ou empresa" value={form.payee} /><SelectField label="Loja" onChange={(store) => onChange({ ...form, store })} options={storeOptions} value={form.store} /><TextField label="Valor mensal" onChange={(e) => onChange({ ...form, amount: formatBRL(e.target.value) })} placeholder="R$ 0,00" value={form.amount} /><TextField label="Dia do vencimento" onChange={(e) => onChange({ ...form, dueDay: e.target.value })} placeholder="10" type="number" value={form.dueDay} /><TextField label="Alertar com antecedência" onChange={(e) => onChange({ ...form, alertDays: e.target.value })} placeholder="5" type="number" value={form.alertDays} /><button className="mt-7 h-11 rounded-md bg-slate-950 px-4 text-sm font-semibold text-white" onClick={onSubmit} type="button">Cadastrar recorrência</button></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{expenses.map((item) => <article className="rounded-lg border border-slate-200 bg-white p-5 shadow-sm" key={item.id}><div className="flex justify-between gap-3"><div><span className="text-xs font-semibold uppercase text-cyan-700">{item.category}</span><h3 className="mt-1 font-semibold">{item.name}</h3><p className="text-sm text-slate-500">{item.payee} · {item.store}</p></div><CalendarClock className="text-slate-400" size={20} /></div><strong className="mt-4 block text-lg">{item.amount}</strong><div className="mt-3 flex items-center gap-2 text-xs text-amber-800"><Bell size={14} />Vence todo dia {item.dueDay}; alerta {item.alertDays} dia(s) antes</div></article>)}</div></div>;
}
